In [1]:
import numpy as np
import pandas as pd

# loading the dataset

In [2]:
patient_data = pd.read_csv(r"C:\Users\dusan\OneDrive\Pictures\Documents\PROJECT\Healthcare-Patient-Analysis_02\data\healthcare_dataset.csv")
df = pd.DataFrame(patient_data)
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Tiffany Ramirez,81,Female,O-,Diabetes,2022-11-17,Patrick Parker,Wallace-Hamilton,Medicare,37490.983364,146,Elective,2022-12-01,Aspirin,Inconclusive
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal

# Check :
- Missing values
- Duplicate records
- Unique values
- Incorrect data types
- Invalid values
- Negative values
- Zero values
- Extreme values

# Missing values

In [3]:
missing_value = df.isna().sum()
print(missing_value)

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

# Duplicate records

In [4]:
duplicate = df.duplicated()
duplicate.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

# Incorrect data types

In [5]:
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

# Invalid values
- Negative values
- Zero values
- Extreme values

- for age

In [6]:
age = df[(df['Age'] >= 10) & (df['Age'] <= 80)] 
age.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
1,Ruben Burns,35,Male,O+,Asthma,2023-06-01,Diane Jackson,"Burke, Griffin and Cooper",UnitedHealthcare,47304.064845,404,Emergency,2023-06-15,Lipitor,Normal
2,Chad Byrd,61,Male,B-,Obesity,2019-01-09,Paul Baker,Walton LLC,Medicare,36874.896997,292,Emergency,2019-02-08,Lipitor,Normal
3,Antonio Frederick,49,Male,B-,Asthma,2020-05-02,Brian Chandler,Garcia Ltd,Medicare,23303.322092,480,Urgent,2020-05-03,Penicillin,Abnormal
4,Mrs. Brandy Flowers,51,Male,O-,Arthritis,2021-07-09,Dustin Griffin,"Jones, Brown and Murray",UnitedHealthcare,18086.344184,477,Urgent,2021-08-02,Paracetamol,Normal
5,Patrick Parker,41,Male,AB+,Arthritis,2020-08-20,Robin Green,Boyd PLC,Aetna,22522.363385,180,Urgent,2020-08-23,Aspirin,Abnormal

-  for room number :

In [7]:
room_number = df['Room Number'] >= 0
print(room_number.unique())

[ True]

- for gender

In [8]:
gender = df[df['Gender'] == None]
print(gender)

Empty DataFrame
Columns: [Name, Age, Gender, Blood Type, Medical Condition, Date of Admission, Doctor, Hospital, Insurance Provider, Billing Amount, Room Number, Admission Type, Discharge Date, Medication, Test Results]
Index: []

- for billing amount :

In [9]:
med_cost = df[(df['Billing Amount'] >= 0 )& (df['Billing Amount'] <= 10000)]
med_cost.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
11,Mrs. Caroline Farrell,23,Female,O-,Hypertension,2019-06-09,William Miller,Rose Inc,Medicare,6185.903530,126,Emergency,2019-06-26,Paracetamol,Inconclusive
12,Christina Williams,85,Female,A+,Diabetes,2021-11-29,Laura Roberts,"Malone, Thompson and Mejia",Aetna,4835.945650,444,Elective,2021-12-14,Aspirin,Inconclusive
18,Desiree Williams MD,66,Male,O+,Obesity,2022-06-19,Megan Sanders,Pugh-Rogers,UnitedHealthcare,4262.911578,125,Elective,2022-06-29,Aspirin,Inconclusive
32,Kevin Johnson,78,Male,O-,Asthma,2021-02-06,Michael Smith,"Hernandez, Hunt and Clark",Medicare,9007.967866,247,Urgent,2021-03-03,Lipitor,Abnormal
35,Jennifer Rodriguez,83,Female,AB-,Asthma,2019-11-12,Rachel Sullivan,Duke Group,Cigna,5098.663128,192,Emergency,2019-11-24,Lipitor,Abnormal

- for the dates

In [10]:
df.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object